config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'courses#index'

  resources :users,     only: %i[show new create]
  resources :sessions,  only: %i[new create destroy]

  get     'signup', to: 'users#new',        as: 'signup'
  get     'login',  to: 'sessions#new',     as: 'login'
  delete  'logout', to: 'sessions#destroy', as: 'logout'

  resources :courses, only: %i[index show] do
    post    'groups/:group_id/join',  to: 'courses/participations#create',   as: :join
    delete  'groups/:group_id/leave', to: 'courses/participations#destroy',  as: :leave
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  has_many :groups

  validates :title, presence: true, uniqueness: true

  scope :nearest,  -> { joins(:groups).merge(Group.order(starts_on: :asc)) }
  scope :farthest, -> { joins(:groups).merge(Group.order(starts_on: :desc)) }
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :course
  has_many :participations
  has_many :users, through: :participations

  validates :starts_on, presence: true

  scope :upcoming, -> { where('starts_on > ?', Time.current) }
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user_id, uniqueness: { scope: :group_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :participations
  has_many :groups, through: :participations

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  http_basic_authenticate_with name: 'admin', password: 'admin', if: :admin_controller?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def admin_controller?
    self.class < ActiveAdmin::BaseController
  end
end

app/controllers/courses/participations_controller.rb
# frozen_string_literal: true

class Courses::ParticipationsController < ApplicationController
  before_action :set_course

  def create
    result = ParticipationContainer[:create].call(@course, params[:group_id], current_user.id)

    redirect_to @course, notice: result
  end

  def destroy
    result = ParticipationContainer[:destroy].call(@course, params[:group_id], current_user.id)

    redirect_to @course, notice: result
  end

  private

  def set_course
    @course = Course.includes(:groups).find(params[:course_id])
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  def index
    @courses =
      if params[:filter_by] == 'nearest' || params[:filter_by].nil?
        Course.nearest.includes(groups: :participations).page(params[:page])
      else
        Course.farthest.includes(groups: :participations).page(params[:page])
      end
  end

  def show
    @course = Course.includes(groups: :users).find(params[:id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Email or password is invalid'

      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authorize_user,    only: :edit
  before_action :authenticate_user, only: :show
  before_action :set_user,          only: %i[show destroy]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def authorize_user
    redirect_to root_path, notice: 'You can\'t do that' unless current_user.id == params[:user_id]
  end

  def authenticate_user
    redirect_to root_path, notice: 'You must be logged in' unless current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
  def participants_number(course)
    course.groups.flat_map(&:participations).size
  end

  def beginning_date(course)
    course.groups.upcoming.first.starts_on
  end

  def ordering_link(filter_by)
    if filter_by == 'nearest' || filter_by.nil?
      link_to 'Starts on 🔽', courses_path(filter_by: :farthest), id: 'sort_courses'
    else
      link_to 'Starts on 🔼', courses_path(filter_by: :nearest), id: 'sort_courses'
    end
  end
end

app/views/courses/index.html.slim
h1 Courses

table border=1
  tr
    th Title
    th = ordering_link(params[:filter_by])
    th Students
  tbody
    - @courses.each do |course|
      tr
        td = link_to course.title, course
        td = beginning_date(course)
        td = participants_number(course)

app/views/courses/show.html.slim
h1 = "#{@course.title} course"

- if @course.groups.upcoming.any?
  h3 Upcoming groups
  table border=0
    tr
      th Starts on
      th colspan=2 Students participating
    - @course.groups.upcoming.each do |group|
      tr
        td = group.starts_on
        td
          - if group.participations.any?
            ul
              - group.participations.each do |participation|
                li = participation.user.email
          - else
            p N/A
        td
          - if group.users.include?(current_user)
            = link_to 'Leave', course_leave_path(@course, group), method: :delete, data: { confirm: 'Are you sure?' }
          - else
            = link_to 'Join', course_join_path(@course, group), method: :post

- else
  p There are no upcoming groups for this course

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekbrainsTestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Courses', courses_path %>

      <% if current_user %>
        Logged in as <%= current_user.email %>
        <%= link_to 'Log Out', logout_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign Up', signup_path %> or
        <%= link_to 'Log In', login_path %>
      <% end %>
    </p>

    <%= render 'shared/flashes', flash: flash %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.slim
- flash.each do |key, message|
  p class="#{key}"
    = message

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p
  strong Email:
  = @user.email

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path